# secrets with RDS username and password

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.regcred.name }}
data:
  .dockerconfigjson: {{ .Values.secret.regcred.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.dbcred.name }}
data:
  DB_USERNAME: {{ .Values.secret.dbcred.dbUserName }}
  DB_PASSWORD: {{ .Values.secret.dbcred.dbPassword }}